import pandas as pd


configfile: "config/config.yaml"

# print(config.keys())
SAMPLES_INFO = pd.read_csv(config["samplesheet"], sep="\t", dtype={"sample_id": str})
TRAIN_SAMPLES = SAMPLES_INFO[SAMPLES_INFO["purpose"] == "train"].set_index("sample_id", drop=False).sort_index()
BENCH_SAMPLES = SAMPLES_INFO[SAMPLES_INFO["purpose"] == "bench"].set_index("sample_id", drop=False).sort_index()


# print(TRAIN_SAMPLES.loc["NA12878"]["query_vcf"])

wildcard_constraints:
    sample_id = "|".join(TRAIN_SAMPLES.index.tolist() + BENCH_SAMPLES.index.tolist())


# sys.exit(0)
rule all:
    input:
        "results/happy_plot/{prefix}_apply_snp_happy_summary.png".format(prefix=config["prefix"]),
        "results/happy_plot/{prefix}_apply_indel_happy_summary.png".format(prefix=config["prefix"])
        

rule extract_features:
    input:
        train_vcf=lambda wc: TRAIN_SAMPLES.loc[wc.sample_id]["query_vcf"],
        train_vcf_index=lambda wc: TRAIN_SAMPLES.loc[wc.sample_id]["query_vcf_index"],
        train_truth_vcf=lambda wc: TRAIN_SAMPLES.loc[wc.sample_id]["truth_vcf"],
        train_truth_vcf_index=lambda wc: TRAIN_SAMPLES.loc[wc.sample_id]["truth_vcf_index"],
        train_bed=lambda wc: TRAIN_SAMPLES.loc[wc.sample_id]["bed"]
    output:
        snp_matrix="results/features/{prefix}_{sample_id}_snp_feature_matrix.tsv",
        indel_matrix="results/features/{prefix}_{sample_id}_indel_feature_matrix.tsv"
    params:
        prefix=f"results/features/{config['prefix']}"+"_{sample_id}",
        vcf_filter_flag=config["extract_features"]["vcf_filter_flag"],
        info_flag_snp=config["extract_features"]["info_flags_snp"],
        info_flag_indel=config["extract_features"]["info_flags_indel"]
    shell:
        """
        python workflow/scripts/extract_features.py {input.train_vcf} \
            {input.train_truth_vcf} \
            {input.train_bed} \
            {params.prefix} \
            --sample-id {wildcards.sample_id} \
            --vcf-filter-flag "{params.vcf_filter_flag}" \
            --info-flags-snp "{params.info_flag_snp}" \
            --info-flags-indel "{params.info_flag_indel}"
        """

rule train_model:
    input:
        # features_file=expand("results/features/{samples}_{var_type}_feature_matrix.tsv", samples=TRAIN_SAMPLES.index),
        features_file = lambda wc: expand(
            "results/features/{prefix}_{samples}_{var_type}_feature_matrix.tsv", 
            prefix=config["prefix"], 
            samples=TRAIN_SAMPLES.index, 
            var_type=wc.var_type
        ),
        train_model_config_file=config["train_model"]["config_file"]
    params:
        info_flags=lambda wc: config["train_model"][f"info_flags_{wc.var_type}"],
        # model=config["train_model"]["model_names"]
        model="{model_name}"
    output:
        model_file=f"results/models/{config['prefix']}"+"_{model_name}_{var_type}.pkl",
    shell:
        """
        python workflow/scripts/train_model.py \
              -i {input.features_file} \
              -o {output.model_file} \
              --info-flags {params.info_flags} \
              -c {input.train_model_config_file} \
              --model {params.model}
        """
    
rule apply_model:
    input:
        model_file=f"results/models/{config['prefix']}"+"_{model_name}_{var_type}.pkl",
        test_vcf=lambda wc:BENCH_SAMPLES.loc[wc.sample_id]["query_vcf"],
        test_vcf_index=lambda wc:BENCH_SAMPLES.loc[wc.sample_id]["query_vcf_index"],
    params:
        batch_size=config["apply_model"]["batch_size"],
        filter_name=config["apply_model"]["filter_name_prefix"],
        var_type="{var_type}",
        overwrite_filter="-F" if config["apply_model"]["overwrite_filter"] else ""
    output:
        vcf=f"results/apply/{config['prefix']}"+"_{sample_id}_{model_name}_apply_{var_type}.vcf.gz",
        vcf_index=f"results/apply/{config['prefix']}"+"_{sample_id}_{model_name}_apply_{var_type}.vcf.gz.tbi"
    shell:
        """
        python workflow/scripts/apply_model.py \
            -i {input.test_vcf} \
            -m {input.model_file} \
            -o {output.vcf} \
            -t {params.var_type} \
            -f {params.filter_name}_{params.var_type}_FAIL \
            {params.overwrite_filter}
        tabix {output.vcf}
        """

rule merge_snp_indel:
    input:
        snp_vcf=f"results/apply/{config['prefix']}"+"_{sample_id}_{model_name}_apply_snp.vcf.gz",
        snp_v_index=f"results/apply/{config['prefix']}"+"_{sample_id}_{model_name}_apply_snp.vcf.gz.tbi",
        indel_vcf=f"results/apply/{config['prefix']}"+"_{sample_id}_{model_name}_apply_indel.vcf.gz",
        indel_v_index=f"results/apply/{config['prefix']}"+"_{sample_id}_{model_name}_apply_indel.vcf.gz.tbi"
    output:
        vcf=f"results/merge_apply/{config['prefix']}"+"_{sample_id}_{model_name}_apply.vcf.gz",
        vcf_index=f"results/merge_apply/{config['prefix']}"+"_{sample_id}_{model_name}_apply.vcf.gz.csi"
    shell:
        """
        bcftools concat -a -O z -W -o {output.vcf} {input.snp_vcf} {input.indel_vcf}
        """

rule hap_py:
    input:
        truth=lambda wc:BENCH_SAMPLES.loc[wc.sample_id]["truth_vcf"],
        truth_index=lambda wc:BENCH_SAMPLES.loc[wc.sample_id]["truth_vcf_index"],
        query=f"results/merge_apply/{config['prefix']}"+"_{sample_id}_{model_name}_apply.vcf.gz",
        query_index=f"results/merge_apply/{config['prefix']}"+"_{sample_id}_{model_name}_apply.vcf.gz.csi",
        truth_regions=lambda wc:BENCH_SAMPLES.loc[wc.sample_id]["bed"],
        genome=config["hap_py"]["ref_fasta"],
        genome_index=config["hap_py"]["ref_fasta_index"]
    output:
        f"results/happy/{config['prefix']}"+"_{sample_id}_{model_name}_apply_happy.summary.csv"
    params:
        prefix=f"results/happy/{config['prefix']}"+"_{sample_id}_{model_name}_apply_happy"
    threads: 4
    log: f"results/happy/{config['prefix']}"+"_{sample_id}_{model_name}_apply_happy.log"
    wrapper: "v7.0.0/bio/hap.py/hap.py"

rule plot_hap:
    input:
        hap_summary_files = expand("results/happy/{prefix}_{sample_id}_{model_name}_apply_happy.summary.csv", 
                                    prefix=config["prefix"], 
                                    sample_id=BENCH_SAMPLES.index, 
                                    model_name=config["train_model"]["model_names"])
    output:
        # "results/hap_plot/test_dev.snp.hap.summary.png",
        # "results/hap_plot/test_dev.indel.hap.summary.png"
        snp_png=f"results/happy_plot/{config['prefix']}_apply_snp_happy_summary.png",
        indel_png=f"results/happy_plot/{config['prefix']}_apply_indel_happy_summary.png"
    params:
        sample_ids=[s for s in BENCH_SAMPLES.index for _ in range(len(config["train_model"]["model_names"]))],
        # tags = expand("{model_name}", sample_id=BENCH_SAMPLES.index, model_name=config["train_model"]["model_names"])
        tags = [ m for _ in BENCH_SAMPLES.index for m in config["train_model"]["model_names"]]
    shell:
        """
        python workflow/scripts/plot_hap.py -i {input.hap_summary_files} \
              -o {output.snp_png} \
              -s {params.sample_ids} \
              -t {params.tags} \
              --type SNP \
              --filter PASS
        python workflow/scripts/plot_hap.py -i {input.hap_summary_files} \
              -o {output.indel_png} \
              -s {params.sample_ids} \
              -t {params.tags} \
              --type INDEL \
              --filter PASS
        """