name: find-variant-filter
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10,<3.13
  - snakemake
  - pysam
  - pandas
  - numpy
  - scikit-learn
  - joblib
  - matplotlib
  - seaborn
